version: "3.9"

services:
  app:
    container_name: rental_mobil_app
    image: node:20.11.0-alpine
    depends_on:
      - database
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./:/app
    command:
      - /bin/sh
      - -c
      - |
        echo "Installing Depedency.."
        npm i > /dev/null 2>&1
        npm start

  database:
    container_name: rental_mobil_db
    image: mysql:8.0.31
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=superadminwe
    ports:
      - 3307:3306
    volumes:
      - ./rental_mobil.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    command: --default-authentication-plugin=mysql_native_password

  web_server:
    container_name: rental_mobil_web_server
    image: nginx:1.25-alpine
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
